version: "3.9"
services:
  svc:
    build:
      context: .
      network: host
    ports:
      - 8080:8080
    environment:
      - SVC_PORT=8080
      - SVC_ENVIRONMENT=dev
      - SVC_VERSION=v0.0.0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=langlearnsvc
      - DB_PASSWORD=simple

  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: langlearnsvc
      POSTGRES_PASSWORD: simple
      POSTGRES_DB: langlearndb
    restart: always
    volumes:
      - ./db/relational:/docker-entrypoint-initdb.d:z